### PR TITLE
Revert dynamic constraint updates for matter-thermostat and matter-sensor

### PR DESCRIPTION
**Pull request by nickolas-deboom**
Support for temperature conversion for the temperatureRange, coolingSetpointRange, and heatingSetpointRange capabilites was added by [this PR ](https://github.ecodesamsung.com/iot-hub/hub-core/pull/7086/files). This change introduced a bug that causes an error when temperature conversion is attempted for these capabilites. See the [Temperature Conversion Issue](https://smartthings.atlassian.net/wiki/spaces/~7120201ec2fa4a1b0548dd86df78b89d08422e/pages/3110142325/Dynamic+Capability+Constraints#Temperature-Conversion-Issue) for more background information. Also see section [Reverting Dynamic Constraints Changes](https://smartthings.atlassian.net/wiki/spaces/~7120201ec2fa4a1b0548dd86df78b89d08422e/pages/3110142325/Dynamic+Capability+Constraints#Reverting-Dynamic-Constraint-Changes) for information about testing this change.

This PR will revert the dynamic constraint updates originally made in matter-thermostat ([PR 1223](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1223)) and matter-sensor ([PR 1224](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1224)) until the bug is fixed in the next firmware release. After that point, a new PR will be created to restore these changes.

Jira ticket: [CHAD-13444](https://smartthings.atlassian.net/browse/CHAD-13444)

[CHAD-13444]: https://smartthings.atlassian.net/browse/CHAD-13444?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by ctowns — COMMENTED** [review]
This looks pretty good to me! Quick question - was this a pure revert of the two original commits? If it was it might be a good idea to just document the commit SHAs that were reverted in the PR comment or in one of the commit messages.

Also, remember to squash your commits!

**Review by hcarter-775 — APPROVED** [review]

**Comment by hcarter-775** [comment]
yeah this looks good to me as well! I like @ctowns idea to comment as well, but conditionally approved :+1:

**Comment by nickolas-deboom** [comment]
> This looks pretty good to me! Quick question - was this a pure revert of the two original commits? If it was it might be a good idea to just document the commit SHAs that were reverted in the PR comment or in one of the commit messages.
> 
> Also, remember to squash your commits!

It was a revert of the two PRs (one commit for matter-sensor and several for matter-thermostat after not squashing those commits...) plus some additional changes were needed in the test cases from changes that took place after the original two PRs, in order to make sure we're not subscribing to the min/max setpoint and temperature range attributes in test cases developed since that time. Do you think I should still list the commits? Maybe listing the two PRs might be best since it would be a list of about 17 commits?

**Comment by ctowns** [comment]
> > This looks pretty good to me! Quick question - was this a pure revert of the two original commits? If it was it might be a good idea to just document the commit SHAs that were reverted in the PR comment or in one of the commit messages.
> > Also, remember to squash your commits!
> 
> It was a revert of the two PRs (one commit for matter-sensor and several for matter-thermostat after not squashing those commits...) plus some additional changes were needed in the test cases from changes that took place after the original two PRs, in order to make sure we're not subscribing to the min/max setpoint and temperature range attributes in test cases developed since that time. Do you think I should still list the commits? Maybe listing the two PRs might be best since it would be a list of about 17 commits?

Oh yeah no worries, if it's 17 commits I wouldn't worry about listing them all out!

Just remember to squash the commits on this PR - you can do it in the GitHub GUI or in your local repo and just force push the squashed commits. The GitHub GUI makes it pretty straightforward though :)

**Review by ctowns — APPROVED** [review]

**Pull request merged**
