### PR TITLE
Add device configuration for matter-fan

### PR DESCRIPTION
**Pull request by HunsupJung**
The matter-fan driver uses airCondtionerFanMode and its label is "Air Condtioner Fan Mode".
This is for changing a label to "Fan Mode"  from "Air Conditioner Fan Mode"

### CODE REVIEW

**Comment by ctowns** [comment]
I believe this will solve the issue in the future when we can use this: https://github.ecodesamsung.com/iot/SmartThingsCapabilities/pull/351

@HunsupJung could we wait for the new capability to use here, or do we need to make this change now?

**Comment by HunsupJung** [comment]
We can use Fan Mode capability that you made. Thank you 👍

**Comment by HunsupJung** [comment]
@ctowns  When should we change the airConditionFanMode to the newly created Fan Mode capability?

**Comment by HunsupJung** [comment]
@ctowns 
Can we use this PR until creating new Fan Mode capability?

**Review by ctowns — APPROVED** [review]

**Review by hcarter-775 — APPROVED** [review]
Yes, I think using this until we release the new capability is good.

**Pull request merged**
