### PR TITLE
Remove embedded clusters from CI coverage results

### PR DESCRIPTION
**Pull request by ctowns**

### CODE REVIEW

**Comment by ctowns** [comment]
This looks good to me, but I cannot approve since I am the owner :)

**Review by nickolas-deboom — APPROVED** [review]

**Review by cjswedes — APPROVED** [review]

**Comment by greens** [comment]
why are the tests failing?

**Review by greens — APPROVED** [review]
Or was that just a way to force the CI to run the tests?

**Comment by hcarter-775** [comment]
Yes, that was just a way to force the tests to run. Then we re-added the lines from each init.lua function that were removed to cause failing tests, and will only push the .luacov change.

**Pull request merged**
