### PR TITLE
Added fingerprints for  Heatit Z-TRM2 and Z-TRM3 (fingerprints.yml)

### PR DESCRIPTION
**Pull request by fredrile**
Added fingerprints for Heatit Z-TRM2 and Z-TRM3

### CODE REVIEW

**Comment by veonua** [comment]
@fredrile can you please click these buttons

**Comment by fredrile** [comment]
> @fredrile can you please click these buttons

You mean the CLA? If so, It´s signed.

**Comment by veonua** [comment]
@greens please review

**Comment by lelandblue** [comment]
Hello - We are closing this PR. If you would like to pursue WWST Certification please reach out to partners@smartthings.com.

**Pull request closed without merging**
