### PR TITLE
Integration device NodOn

### PR DESCRIPTION
**Pull request by AltyorFig**
Hello, 

I am migrating my products previously on the old version to Edge smartthings.

We have added 6 products distributed as follows:

fingerprint zigbee-switch
SIN-4-1-20 + SIN-4-1-20-PRO

fingerprint zigbee-window-treatment
SIN-4-RS-20+SIN-4-RS-20-PRO

fingerprint zigbee-multi-switch-v4.5-childs-edge from Mariano code
SIN-4-2-20 + SIN-4-2-20-PRO

We have tested them and submit them to you for verification in order to be able to certify them afterwards.

Best regards

Emilie

### CODE REVIEW

**Review by ecolo31 — COMMENTED** [review]
Add 6 devices from NodOn:
-fingerprint zigbee-switch
SIN-4-1-20 + SIN-4-1-20-PRO

-fingerprint zigbee-window-treatment
SIN-4-RS-20+SIN-4-RS-20-PRO

-fingerprint zigbee-multi-switch-v4.5-childs-edge from Mariano code
SIN-4-2-20 + SIN-4-2-20-PRO

**Comment by Mariano-Github** [comment]
> fingerprint zigbee-multi-switch-v4.5-childs-edge from Mariano code SIN-4-2-20 + SIN-4-2-20-PRO
> 
> We have tested them and submit them to you for verification in order to be able to certify them afterwards.
> 
> Best regards
> 
> Emilie


Hi Emily,

I don't understand how you have submitted a driver that is not yours for certification and without asking for any permission to do so.

I added the fingerprints of your devices so that you could test how it works with an edge driver, but in no case did you comment on submitting this driver to a smartthings certification.

**This was his question on github:**
Hi @Mariano-Github , Thanks for your answer. After testing device, how can we pull request to smart things? Is it recognize for adding product in the console for company like others?

**This was my answer to your question:**
hi,

This driver is not an official driver, it is a personal driver.

If you want to add the fingerprints to the smartthings Zigbee Switch driver you will have to make a pull request on the github smartthings beta drivers

https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/tree/production/drivers

This driver has many fingerprints from many devices that are from different manufacturers.

As I told you, you can add the fingerprints of the your dual switch devices in the Zigbee Switch stock beta, since it also supports multi-component devices.

Best regards
Mariano Colmenarejo

**Comment by AltyorFig** [comment]
Hi @Mariano-Github ,

I'm really sorry for the misunderstanding. I am new to the world of integration. I didn't want to harm you. I misinterpreted your last message by understanding that I had to integrate your code into a pull request. 
I cancel this step especially if you tell me that the switch module allows you to do double endpoint. I apologize again for the damage I have caused you. Thank you for all the help you have given me.

Best regards,
Emilie FIGUIE

**Comment by Mariano-Github** [comment]
> I'm really sorry for the misunderstanding.

Do not worry there is no problem.
My driver does not meet the requirements for smartthings, custom capabilities...others

**Pull request closed without merging**
