### PR TITLE
[Sonos] Correct Alignment of mediaGroup Commands & CmdHandlers

### PR DESCRIPTION
**Pull request by TheMegamind**
This replaces #575, which had an improperly merged commit on an unrelated issue. Revised by request.

### CODE REVIEW

**Comment by TheMegamind** [comment]
@dljsjr Here's the revised PR. In the end, it was easier for me to close the previous PR & resubmit.

**Review by dljsjr — APPROVED** [review]

**Review by dljsjr — CHANGES_REQUESTED** [review]
These should actually be `CmdHandlers.handle_group_*`:

https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/601/files#diff-fd98e5f9cd685da688b3464a6b348e53d4ae6b64630cd49d185ea8d5a05a3ed6R230

**Comment by TheMegamind** [comment]
Ah, I wondered about the lack of group reference in those commands previously, but just went along with what was already in init.lua. I assume this is what you need.  

https://github.com/TheMegamind/SmartThingsEdgeDrivers/compare/main...TheMegamind-patch-1

**Comment by dljsjr** [comment]
@TheMegamind Looks good! You can submit a new PR or put that in here as a [fixup commit](https://blog.sebastian-daschner.com/entries/git-commit-fixup-autosquash) and squash it down.

**Comment by TheMegamind** [comment]
I need to learn to do the fixup & squash properly, but not here, not now. lol

**Pull request closed without merging**
