### PR TITLE
Fixes tests that will fail because of v45's release

### PR DESCRIPTION
**Pull request by greens**

### CODE REVIEW

**Review by varzac — APPROVED** [review]

**Comment by cjswedes** [comment]
Do you know what is up with these tests?
```
##################################
Total unit tests passes: 2353/2371
##################################
Unit test failures in /home/runner/work/SmartThingsEdgeDrivers/SmartThingsEdgeDrivers/drivers/SmartThings/zwave-thermostat/src/test/test_qubino_flush_thermostat.lua:
    Setup Mode should be changed after changing updating preferences
Unit test failures in /home/runner/work/SmartThingsEdgeDrivers/SmartThingsEdgeDrivers/drivers/SmartThings/zwave-switch/src/test/test_zooz_switch.lua:
    Refresh capability should evoke the correct Z-Wave GETs
Unit test failures in /home/runner/work/SmartThingsEdgeDrivers/SmartThingsEdgeDrivers/drivers/SmartThings/zwave-switch/src/test/test_switch_multicomponent_meter_2.lua:
    Binary switch on/off report from channel 1 should be handled: on
    Zooz - Refresh sends commands to all components including base device
    Multichannel switch on/off capability command on from component 1 should be handled: on
    Zooz - Multichannel switch on/off capability command on from component 2 should be handled: on
    Zooz - Multichannel switch on/off capability command off from main component should be handled: off
    Zooz - Multichannel switch on/off capability command off from switch1 component should be handled: off
    Zooz - Binary switch on/off report from channel 1 should be handled: on
    Zooz - Binary switch on/off report from channel 2 should be handled: on
    Zooz - SwitchBinary reports with value-off from endpoint 1 should evoke Switch capability off events
    Zooz - SwitchBinary reports with value-off from endpoint 2 should evoke Switch capability off events
    Zooz - Energy meter report from endpoint 1 should be handled
    Zooz - Energy meter report from endpoint 2 should be handled
    Zooz - Power meter report from endpoint 1 should be handled
    Zooz - Power meter report from endpoint 2 should be handled
    Zooz - Switch capability off commands from main component should evoke the correct Z-Wave SETs and GETs
    Zooz - Switch capability off commands from switch1 component should evoke the correct Z-Wave SETs and GETs
```

**Comment by greens** [comment]
The thermostat issue is a weird timing bug that I haven't been able to nail down. Doesn't always fail. Doesn't always pass.

**Comment by KKlimczukS** [comment]
> The thermostat issue is a weird timing bug that I haven't been able to nail down. Doesn't always fail. Doesn't always pass.

Same here when I run those tests locally.

**Comment by KKlimczukS** [comment]
```
Unit test failures in /home/runner/work/SmartThingsEdgeDrivers/SmartThingsEdgeDrivers/drivers/SmartThings/zwave-switch/src/test/test_zooz_switch.lua:
    Refresh capability should evoke the correct Z-Wave GETs
```
@cjswedes @greens 
We're trying to sort it out here: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/339
but some decisions needs to be made first.

**Comment by KKlimczukS** [comment]
`Unit test failures in /home/runner/work/SmartThingsEdgeDrivers/SmartThingsEdgeDrivers/drivers/SmartThings/zwave-switch/src/test/test_switch_multicomponent_meter_2.lua:`

I had only issue with this one test (locally /with updated lua libs from the repo):
`Binary switch on/off report from channel 1 should be handled: on`, 

The workaround for that might be to add `current_value` to the report:
```
 message = { mock_aeotec_switch_multicomponent.id,
                  zw_test_utils.zwave_test_build_receive_command(SwitchBinary:Report({ target_value=0xFF, current_value=0xFF },
                  {encap = zw.ENCAP.AUTO, src_channel = 1, dst_channels = {0}}))}
```
but the rest of failing tests might be fixed automatically after we device about Zooz Double switch here: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/339
@greens @cjswedes

**Pull request merged**
