### PR TITLE
Add sinope thermostat th1123zb-g2, change zigbee thermostat deviceLabel

### PR DESCRIPTION
**Pull request by aguilbault-Sinope**

### CODE REVIEW

**Review by greens — APPROVED** [review]

**Comment by greens** [comment]
@aguilbault-Sinope looks like you might have brought in some other changes on accident.

**Comment by aguilbault-Sinope** [comment]
@greens what is missing on this merge request ? I've reverted what I've done, and squashed only my commits. Let me know if I need to do something else to fix it. I havent received news for the next certification steps. Thank you.

**Comment by greens** [comment]
@aguilbault-Sinope next steps will be with whoever is managing your certification request. I have to get the go-ahead from them before we can proceed.

**Comment by lelandblue** [comment]
Hello, @aguilbault-Sinope. Thank you for your message. We have reached out to our partner success team, and they will be in contact shortly.

**Comment by Brianj94** [comment]
Hi Team, just wanted to update here that Sinope has been sent the quote from UL (Jan 3rd), and there are no open questions currently.

**Review by greens — APPROVED** [review]

**Comment by greens** [comment]
@Brianj94 Only guess would be accidentally being on an older version of the driver. The driver info in the device card's menu should say the version being used.

**Comment by Brianj94** [comment]
@greens Okay, I am thinking the same thing. Do you see any issues with the changes Sinope made last week? I know we also had an issue previously pushing the Jan/Feb changes up to the driver channel correctly. I want to make sure that process finishes before pushing to have UL test again. 

Once these latest changes hit the driver channel for this PR I will have Sinope test again and see if the changes work correctly here. Thanks!

**Pull request merged**
