### PR TITLE
fix Aqara Wireless Button E1 reonboarding issue

### PR DESCRIPTION
**Pull request by yejinze**
This is a fix for STSE-2620. Added Test Coverage, but wallhero coverage may not be up to 90%. The function that did not coverage is init function. I cannot access by test using virtual devices.

### CODE REVIEW

**Comment by yejinze** [comment]
This PR is a Test Coverage complement for PR#1295. I made a mistake with "git push -f" in PR#1295. Sorry~!

**Review by greens — COMMENTED** [review]
```
    drivers/SmartThings/zigbee-button/src/test/test_SLED_button.lua:19:7: (W211) unused variable cluster_base
    drivers/SmartThings/zigbee-button/src/test/test_SLED_button.lua:20:7: (W211) unused variable data_types
    drivers/SmartThings/zigbee-button/src/test/test_SLED_button.lua:23:7: (W211) unused variable PowerConfiguration
    drivers/SmartThings/zigbee-button/src/test/test_SLED_button.lua:54:11: (W211) unused variable additional_fields
    drivers/SmartThings/zigbee-button/src/test/test_SLED_button.lua:77:11: (W211) unused variable additional_fields
```

```
    drivers/SmartThings/zigbee-button/src/test/test_wallhero_button.lua:320:1: (W611) line contains only whitespace
```

**Review by greens — APPROVED** [review]
thank you

**Review by greens — CHANGES_REQUESTED** [review]
```
Checking drivers/SmartThings/zigbee-button/src/test/test_SLED_button.lua 3 warnings

    drivers/SmartThings/zigbee-button/src/test/test_SLED_button.lua:19:15: (W113) accessing undefined variable clusters
    drivers/SmartThings/zigbee-button/src/test/test_SLED_button.lua:20:15: (W113) accessing undefined variable clusters
    drivers/SmartThings/zigbee-button/src/test/test_SLED_button.lua:21:22: (W113) accessing undefined variable clusters
```

**Comment by yejinze** [comment]
Sorry! I deleted a header the test code needs. I have modified it. Please review again.

**Review by greens — APPROVED** [review]
Okay. Looks good now. 

The reason the wallhero coverage is only 88% is because in `scenes_cluster_handler` the component is constructed manually:

```
  local button_name = "button" .. ep
  local event = capabilities.button.button.pushed(additional_fields)
  local comp = device.profile.components[button_name]
```
and emitted using `emit_component_event`

rather than relying on the `endpoint_to_component` function by using `emit_event_for_endpoint` so `endpoint_to_component` is never used.

**Comment by yejinze** [comment]
Please just go ahead and merge. The wallhero driver was not developed by me and I don't have the real device for test right now. However, I tried the method you told, it can actually promote the coverage.

zigbee-multi-button/wallhero/init.lua                  49   5      90.74%

   local ep = zb_rx.address_header.src_endpoint.value
-  local button_name = "button" .. ep
   local event = capabilities.button.button.pushed(additional_fields)
-  local comp = device.profile.components[button_name]
-  if comp ~= nil then
-    device:emit_component_event(comp, event)
+  if ep ~= nil then
+    device:emit_event_for_endpoint(ep, event)

**Pull request merged**
