### PR TITLE
[CHAD-8788] zwave-sensor: Set correct range on temperature measurement values

### PR DESCRIPTION
**Pull request by Bhavik-T**
Updated zwave sensor's temperaturemeasurement to have a range of -20C to 100C.

### CODE REVIEW

**Comment by greens** [comment]
@bflorian how does this work for a capability that has units?

**Comment by bflorian** [comment]
@greens temperature ranges in Canvas should alway be in Celsius. There's special handling in the plugin to scale properly depending on the current units specified in the attribute value.

**Review by greens — APPROVED** [review]

**Comment by iplantemn** [comment]
@greens @bflorian updated capability configurations

**Comment by lelandblue** [comment]
Hello @ctowns Please change   "configuration:" to "config:" thank you!

**Pull request merged**
