### PR TITLE
Default capability update for Samjin multipurpose

### PR DESCRIPTION
**Pull request by dwmaxlee**
Default capability (threeAxis) update for Samjin multipurpose

### CODE REVIEW

**Comment by greens** [comment]
The acceleration attribute should get read on add of the device. Is the device not responding?

**Comment by dwmaxlee** [comment]
> 
The device is not reporting the acceleration attribute, even after binding success. Reonboarding the device can solve the issue. Anyway, what QA team said is that UI looks ugly and this patch is our best what we can do.

**Comment by greens** [comment]
This solution may trigger automations when migration happens from DTH-backed devices. We're currently having discussions about alternative approaches.

**Comment by greens** [comment]
@lelandblue correct. @dwmaxlee is that okay?

**Pull request closed without merging**
