### PR TITLE
fp2: use old lunchbox/rest.lua

### PR DESCRIPTION
**Pull request by hdlee27**
Check all that apply

# Type of Change

- [ ] WWST Certification Request
     - If this is your first time contributing code:
          - [ ] I have reviewed the README.md file
          - [ ] I have reviewed the CODE_OF_CONDUCT.md file
          - [ ] I have signed the CLA
     - [ ] I plan on entering a WWST Certification Request or have entered a request through the WWST Certification console at developer.smartthings.com
- [x] Bug fix
- [ ] New feature
- [ ] Refactor

# Checklist

- [x] I have performed a self-review of my code
- [] I have commented my code in hard-to-understand areas
- [x] I have verified my changes by testing with a device or have communicated a plan for testing
- [ ] I am adding new behavior, such as adding a sub-driver, and have added and run new unit tests to cover the new behavior

# Description of Change

# Summary of Completed Tests

### CODE REVIEW

**Comment by ldeora** [comment]
This one finally works for me. Doing some more testing (deleting and adding several times in a row) later today (may take hours).

Instructed some affected users to test this driver with their environment - waiting for feedback.

**Comment by ldeora** [comment]
Food for thought: What would happen if the current production driver suddenly worked after the driver from this PR worked, which I will test later. That would mean that the cache and/or the fields would survive a delete/add. I don't know how persistent the fields are stored. The fields contain everything important for the adding to work.

That would explain why some users don't have any issues at all. Users with the installed production version of the drivers who tried to add the device to ST the very first time. Not like those users who tried it before with the very first version from the PR!

Just thinking out loud...

**Comment by ldeora** [comment]
Sooo...

I tested it now back and forth:

Installed driver from this PR: works
Installed driver from main, production, beta: doesn't work
Installed driver from this PR again: works
Installed driver from main, production, beta: doesn't work
Installed driver from this PR again: works

Between driver changes, the exact same procedure: delete/add device in Aqara Home app, scan in ST.

**This is the proof that the lunchbox update broke the driver!**

**Review by varzac — APPROVED** [review]

**Comment by ldeora** [comment]
Someone **without** this issue must test this before it gets merged. @seojune79 for example said, that every version works for him.

Then it should go into production asap, before users are giving up.

**Comment by dljsjr** [comment]
Thanks for this @ldeora 

Wanted to let you know that we reviewed the Hue and Sonos code that uses a vendored version of this library as well, and these changes were *not* made in those drivers. Only the Aqara driver. Just wanted to do our diligence since we suspect there's an issue here. We'll be expediting this to production.

**Comment by ldeora** [comment]
That's good to know! Thanks for the information.

**Pull request merged**
