### PR TITLE
Fix tests to reflect v46 changes

### PR DESCRIPTION
**Pull request by greens**

### CODE REVIEW

**Comment by greens** [comment]
The rest of these are matter thermostat bugs that should be fixed by: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/370

**Review by ctowns — APPROVED** [review]
Looks good to me. For future reference, where could I find the "v46 changes"?

**Review by cjswedes — APPROVED** [review]

**Comment by greens** [comment]
@ctowns CHANGELOG.md in the scripting-engine repo, if we all did our jobs right.

**Comment by greens** [comment]
forgot to squash my commits. sorry

gonna go put on my dunce cap

**Pull request merged**
