### PR TITLE
changed profile name in motion.yml

### PR DESCRIPTION
**Pull request by pInksenberg**

### CODE REVIEW

**Comment by pInksenberg** [comment]
In device init lifecycle. A Matter Sensor will check and update its capabilities by running check_for_battery in init.lua.
Then, device:try_update_metadata({profile = profile_name}) will be executed. 

However, since there is no profile named "motion", even though the profile name in motion.yml is "matter-motion", the execution of device:try_update_metadata({profile = profile_name}) will fail.

**Review by wangjinliang12345 — APPROVED** [review]
approve request

**Comment by pInksenberg** [comment]
hello @greens ,  can you help us with verification?

**Review by xixidodo — APPROVED** [review]

**Comment by pInksenberg** [comment]
hello @ctowns , cloud you plz help to review?

**Comment by ctowns** [comment]
Hello @pInksenberg! Before we make this change, we must confirm that the profile with the name `matter-motion` is not currently being used by devices, or else changing the name could result in some devices losing their profile presentation.

@hcarter-775 is working on a similar change to clean up the profile names here: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1466

I believe he has confirmed we can safely make this change, so we will incorporate this as a part of #1466

**Comment by hcarter-775** [comment]
[This PR](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1466), mentioned above by @ctowns, handles the issue in this PR and has finally been merged to main. Therefore, this PR can safely be closed.

**Pull request closed without merging**
