### PR TITLE
add thirdreality smart plug with power

### PR DESCRIPTION
**Pull request by weihuan1111**

### CODE REVIEW

**Comment by weihuan1111** [comment]
@greens  please help to review the merge require, thanks

**Comment by weihuan1111** [comment]
@greens we have changed our plugv2(with power function) model to 3RSP02028BZ,
and plugv1(without power function) model still be 3RSP019BZ
please help to review the merge require, thanks

**Review by greens — APPROVED** [review]

**Comment by weihuan1111** [comment]
@greens Can you help to to review the merge require, thanks

**Comment by Brianj94** [comment]
Hi @weihuan1111, before we can merge these changes we will need to make sure the devices are Works with SmartThings certified. Could I have you reach out to me @ brian.jeffers@smartthings.com or provide an email for me to reach out to you? Thanks!

**Comment by weihuan1111** [comment]
you can reach out to me via ***@***.*** Original ------------------From: Brianj94  ***@***.***>Date: Tue,Dec 20,2022 5:09 AMTo: SmartThingsCommunity/SmartThingsEdgeDrivers ***@***.***>Cc: weihuan1111 ***@***.***>, Mention ***@***.***>Subject: Re: [SmartThingsCommunity/SmartThingsEdgeDrivers] add thirdrealitysmart plug with power (PR #435)
Hi @weihuan1111, before we can merge these changes we will need to make sure the devices are Works with SmartThings certified. Could I have you reach out to me @ ***@***.*** or provide an email for me to reach out to you? Thanks!

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/435#issuecomment-1358368186",
"url": "https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/435#issuecomment-1358368186",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by weihuan1111** [comment]
> Hi @weihuan1111, before we can merge these changes we will need to make sure the devices are Works with SmartThings certified. Could I have you reach out to me @ [brian.jeffers@smartthings.com](mailto:brian.jeffers@smartthings.com) or provide an email for me to reach out to you? Thanks!

@Brianj94 you can reach out to me via @ [huan.wei@thirdreality.ai]

**Comment by weihuan1111** [comment]
@Brianj94 When this pull request can be merged and any other information we need to provide?

**Comment by weihuan1111** [comment]
@Brianj94 When this pull request can be merged and any other information we need to provide?

**Comment by Brianj94** [comment]
Hi @weihuan1111, Thank you for following up. I will be sending over next steps and status update to you via email in just a moment. 

In short the device will need to be tested by our testing partner to ensure it works properly on the platform. Once those tests are passed we can merge the code. There are a few steps we have to take before the device can be tested, but more details coming your way in just a moment. 

Thanks!

**Comment by weihuan1111** [comment]
@Brianj94 When this pull request can be merged and any other information we need to provide?

**Comment by Brianj94** [comment]
Hello @weihuan1111, UL testing labs sent over a pre-quote for testing to support@3reality.com on February 10th. The quote should have came from sheila.reid@ul.com. Once this pre-quote is approved, UL will send the official quote and begin testing. Once the devices pass UL testing, we will merge this PR.

If you have any questions please feel free to email me directly at Brian.jeffers@smartthings.com. Thanks!

**Comment by weihuan1111** [comment]
reopen

**Comment by weihuan1111** [comment]
@Brianj94 We have change the deviceProfileName to switch-power-energy, and create a new pull request : [](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/612) .  Do i need to resubmit certification on Developer Console?

**Comment by Brianj94** [comment]
Hi @weihuan1111, yes I recommend cancelling the previous request and submitting a new request with the updated information and PR.

Thanks!

**Pull request closed without merging**
