### PR TITLE
Add gledopto rgbw controller fingerprint

### PR DESCRIPTION
**Pull request by Felixowns**
Added fingerprint for gledopto rgbw controller to use 2000k-6500k temperature range.

### CODE REVIEW

**Comment by lelandblue** [comment]
Hey @Felixowns Thank you for opening a PR. If you are associated with the device manufacturer please reach out to partners@smartthings.com to start the WWST certification process for this device, if you haven't already. 

Thank you.

**Comment by Felixowns** [comment]
I am not the device manufacturer. Just updating an error in their product because the default driver profile for this model of their controller has the wrong setttings.

**Comment by Felixowns** [comment]
Any update to when this edit can be merged. Really would love to control my lights to the proper values again.

**Comment by lelandblue** [comment]
Hey @Felixowns Thank you for your communication. 

At this time we do not accept new fingerprints for devices that are not going through our WWST Process. 

In order to service your bulb to have it join to the profile you specified, you can create your own driver and load it on to your hub using the SmartThings CLI. If you want to share it with others you may also use Driver Sharing through channels. For more infromation please check out https://developer.smartthings.com and our SmartThings Community at https://community.smartthings.com/

Thank you.

**Pull request closed without merging**
