### PR TITLE
[Aqara/Motion Sensor] The illuminance Measurement capability was modified its range.

### PR DESCRIPTION
**Pull request by seojune79**
The illuminance Measurement capability was modified from [0, 100000] to [0, 1000] according to the illuminance range of the feature of the Aqara device.

### CODE REVIEW

**Comment by greens** [comment]
Ranges can now be modified in profiles without the use of custom metadata. Please see here for an example:

https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/blob/main/drivers/SmartThings/zigbee-switch/profiles/color-temp-bulb-2200K-4000K.yml#L13

We'd prefer you use this method as it is more transparent.

**Review by greens — APPROVED** [review]

**Comment by seojune79** [comment]
Thank you for your help.

**Comment by Kwang-Hui** [comment]
please note we decided to close (cancel) this pull-request.
we found device could report over 1000 lux in some cases which could lead out-of-range screen to users.
@seojune79 , could you close this pull-request?

**Comment by seojune79** [comment]
> please note we decided to close (cancel) this pull-request. we found device could report over 1000 lux in some cases which could lead out-of-range screen to users. @seojune79 , could you close this pull-request?

Yes.

**Comment by seojune79** [comment]
> please note we decided to close (cancel) this pull-request. we found device could report over 1000 lux in some cases which could lead out-of-range screen to users. @seojune79 , could you close this pull-request?

Yes, I could. thank you.

**Pull request closed without merging**
