### PR TITLE
Eve Energy: fix can handle and get switch state on child add

### PR DESCRIPTION
**Pull request by ctowns**
When a child device is added, request the switch state. This is done to account for a race condition where a subscription report arrives before the child device has been created and the child device misses the initial state.

### CODE REVIEW

**Review by greens — COMMENTED** [review]
I'm going to be that guy and suggest you write a test.

**Comment by ctowns** [comment]
@greens Good call out on the test - I wrote a test to check this in the sub driver and this revealed that the `can_handle` check for the sub driver was failing for child devices. This means the added event was actually defaulting to being handled by the parent driver.

Technically, this means that this PR or https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1213 could address the child initial refresh issue since this creates an added handler in the parent driver, which would be used by child devices in this driver when the `can_handle` function fails. However, it would be better fix the `can_handle` function as I have done here. My only concern is that it may not be safe to call the `get_parent_device` function in the `can_handle` function due to race conditions on device creation. Tomorrow I will confirm that it is safe to call `get_parent_device()` in the `can_handle()` function, and if it is we can merge this PR after it has been tested with a real device.

**Comment by lelandblue** [comment]
Not urgent @ctowns - Can you please review if this PR can be closed ? or if we want to keep it ?

**Comment by ctowns** [comment]
See PR#1213

**Pull request closed without merging**
