### PR TITLE
JBL driver clean commit

### PR DESCRIPTION
**Pull request by varzac**
This is a re-upload of https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/842 to test the latest CI changes.

### CODE REVIEW

**Review by chillcyj — COMMENTED** [review]
Hi @varzac 
Could you pull the latest code from main (https://github.com/cchillerr/SmartThingsEdgeDrivers), we have just applied a patch to improve the performance of driver. Thanks.

**Comment by varzac** [comment]
> Hi @varzac Could you pull the latest code from main (https://github.com/cchillerr/SmartThingsEdgeDrivers), we have just applied a patch to improve the performance of driver. Thanks.

You can do this in your own branch, you just need to rebase to include all the latest changes from the main repo in your repo.  I pulled in your changes but your code does not currently pass the linter

```
Checking drivers/SmartThings/jbl/src/discovery.lua 2 warnings

    drivers/SmartThings/jbl/src/discovery.lua:63:9: (W211) unused variable unknown_discovered_devices
    drivers/SmartThings/jbl/src/discovery.lua:64:9: (W211) unused variable known_discovered_devices
```

**Comment by chillcyj** [comment]
Hi @varzac 
The rebase is done, the unused variables are removed. Please have a check, thanks.

**Comment by varzac** [comment]
> Hi @varzac The rebase is done, the unused variables are removed. Please have a check, thanks.

Thank you!  I have updated this PR to include the latest, and I have also run the CI on your PR so both channel invites should use the correct driver now.

**Comment by lelandblue** [comment]
Closing as this went to prod as https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/842

**Pull request closed without merging**
