### PR TITLE
Eve Energy: Improve the performance by grouping multiple attribute reads

### PR DESCRIPTION
**Pull request by Timac**
Improve the performance by grouping multiple attribute reads in one interaction as opposed to multiple interactions

### CODE REVIEW

**Review by ctowns — APPROVED** [review]
Looks good!

**Comment by ctowns** [comment]
There seems to be a recent change in our unit test handling that is causing this to fail. I am currently investigating.

**Comment by ctowns** [comment]
I was not able to address the issue today. However, since these PRs are optimizations rather than fixes, I will plan to hold off until after the holiday to take another look. I can take it from here and I appreciate all your help in making these improvements @Timac - Have a happy holiday! 🎄

**Comment by ctowns** [comment]
I have fixed the unit test issue and put up the fix here: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1153

You can copy the changes from this commit (https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1153/commits/62c54c19823753ae5762bd25953308873f0bb8ee) to your PR and rebase and I can approve and merge this PR, or I can just get approval on my PR tomorrow and get that merged!

**Comment by Timac** [comment]
> I have fixed the unit test issue and put up the fix here: #1153
> 
> You can copy the changes from this commit ([28780bf](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/commit/28780bf01c1b4317708a25bc005ab1b019d48bfd)) to your PR and rebase and I can approve and merge this PR, or I can just get approval on my PR tomorrow and get that merged!

Thanks @ctowns ! I can wait until tomorrow for your PR to be merged

**Comment by ctowns** [comment]
These changes have been merged here: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/1153

**Pull request closed without merging**
