### PR TITLE
CHAD-9856: added Aeon Multisensor 5 fingerprint

### PR DESCRIPTION
**Pull request by sjl2178**
added Aeon Multisensor 5 fingerprint to zwave-sensor driver

https://smartthings.atlassian.net/browse/CHAD-9856

### CODE REVIEW

**Comment by greens** [comment]
Also needs some additions here: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/blob/main/drivers/SmartThings/zwave-sensor/src/configurations.lua#L25

**Comment by sjl2178** [comment]
@greens It looks like its already been added to the matching_matrix? `fingerprint mfr:"0086", prod:"0102", model:"004A"` is the device info which is already under `AOTEC_MULTISENSOR_GEN5`.

**Comment by greens** [comment]
@sjl2178 Looks like the FP you've added already exists in the file

I think you need to add this one:
`mfr: 0086, model: 0005`

and, based on installed devices, this one:
`mfr: 0371, model: 0005`

**Comment by greens** [comment]
I think 0x0371, based on our DTH codebase is another mfr code for Aeotec.

**Comment by sjl2178** [comment]
@greens It seems like both those fps are already present?
`mfr: 0086, model: 0005` is included in `AEON_MULTISENSOR` in the configuration file
https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/blob/845724c8d7720e78b1c23d6518601db5725c09e9/drivers/SmartThings/zwave-sensor/fingerprints.yml#L454

`mfr: 0371, model: 0005` is in `AOTEC_TRISENSOR`
https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/blob/845724c8d7720e78b1c23d6518601db5725c09e9/drivers/SmartThings/zwave-sensor/fingerprints.yml#L73

**Comment by greens** [comment]
you're absolutely correct, so I guess we don't need to do anything here and just need to confirm to Chris that he's testing the right device

**Pull request closed without merging**
