### PR TITLE
add thirdreality smart plug with power

### PR DESCRIPTION
**Pull request by weihuan1111**
Change-Id: I9e7a69d16dfb83a8259ad2c38823c47856882900

### CODE REVIEW

**Comment by weihuan1111** [comment]
@greens

**Comment by weihuan1111** [comment]
We have change the deviceProfileName to switch-power-energy, and create a new pull request
And i close the privious pull request: [](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/435)

**Review by greens — APPROVED** [review]
looks fine pending certification testing

**Comment by weihuan1111** [comment]
@brianj94  Hello, i have cancelled the previous request and submitted a new request with the updated information and PR. What needs to be done next?

**Comment by weihuan1111** [comment]
@greens @brianj94 
Does this driver support Local Execution ?
image

**Comment by Brianj94** [comment]
Hi @weihuan1111, yes this driver does have local execution support. As noted in the test case screenshot you sent, the device will need to have local execution procedures available to handle that activity.

As for next steps, the testing lab (UL) has already been made aware this is the resubmission of the previous certification request. Please have your team reach out to the same contact who sent the pre-quote for the previous submission, and determine if that quote is still valid or if a new quote is required.

Thank you.

**Comment by weihuan1111** [comment]
@Brianj94 Hi, As you said, this driver does have local execution support. But i add the plug to Smartthing app, it seems don't support local execution. And on the web side, it shows Cloud. This is why, and what else do i need to do to make it be local execution. Thank you.
image

**Comment by Brianj94** [comment]
Hi @weihuan1111, thank you for the details. Could I have you send me the Samsung email address for this account and also enable support access using the steps below:

1. Go to my.smartthings.com,
2. Log in to your Samsung account,
3. Select Menu(...) and choose Settings,
4. Toggle on Account Data Access and select a time frame.

I will do some investigation into those devices and hub to see what may be happening there.

Thank you,
Brian J

**Comment by weihuan1111** [comment]
@brianj94  Hi, i have allowed SmartThings Support permission to access to my data for a week. And my account is jiangshanyang@sina.com , thank you.

**Comment by Brianj94** [comment]
Hi @weihuan1111, thanks for the account access. I double checked and confirmed that the devices on this account are all using edge drivers. The IDE environment where you see the Cloud execution status doesn't get an accurate reading for devices using edge drivers, so it defaults to saying Cloud execution. Since the IDE is slowly being deprecated it doesn't always represent the main source of truth.

I also confirmed on my account (where I know I have edge drivers running locally), and it shows the same with all devices saying "cloud execution". If you create an automation with that device you can see a checkmark icon next to it that means the automation is running locally. This is the best way to test and make sure the devices in that automation are all executing locally.

image

**Comment by weihuan1111** [comment]
@Brianj94  Thank you for checking the devices on my account are all using edge drivers. I also have a question, we also have some product which i can not find in the edge drivers, but in privious groovy code, i can see it, such as smart button(model: 3RSB22BZ), smart blind(model: 3RSB015BZ), humi$temp sensor(model:3RTHS24BZ). Does these products still in migrating to edge driver? And when will complete migrateing? Thank you!

**Comment by weihuan1111** [comment]
@Brianj94 Thank you. And i have allowed SmartThings Support permission to access to my data for a week with my another account: huan.wei@thirdreality.ai

**Comment by Brianj94** [comment]
Hi @weihuan1111, I have been looking through the edge drivers and doing a comparison for the devices that are listed on your account. This is my expectation for profile mapping once these devices are migrated to edge drivers. I also recommend certifying these ThirdReality devices so that your team has more control over the profiles and capabilities. 

- ThirdReality Smart Button -> Zigbee-button one-button-battery.yml: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/blob/main/drivers/SmartThings/zigbee-button/profiles/one-button-battery.yml

- ThirdReality Thermal & Humidity Sensor -> Zigbee-humidity-sensor humidity-temp-battery.yml: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/blob/main/drivers/SmartThings/zigbee-humidity-sensor/profiles/humidity-temp-battery.yml

- ThirdReality smart Blind -> zigbee-window-treatment window-treatment-profile.yml: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/blob/main/drivers/SmartThings/zigbee-window-treatment/profiles/window-treatment-profile.yml

We have upcoming driver migrations scheduled for mid April. I can not determine the exact date for your devices being migrated as there are fluid dates for when each specific driver may be migrated. 

I hope this information is helpful. Thanks!

**Comment by weihuan1111** [comment]
@Brianj94 Thank you. Maybe ThirdReality smart Blind -> zigbee-window-treatment window-treatment-battery.yml: [](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/blob/main/drivers/SmartThings/zigbee-window-treatment/profiles/window-treatment-battery.yml)  is better.

**Comment by weihuan1111** [comment]
Maybe ThirdReality smart Blind -> zigbee-window-treatment window-treatment-battery.yml:  [](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/blob/main/drivers/SmartThings/zigbee-window-treatment/profiles/window-treatment-battery.yml)

**Comment by Brianj94** [comment]
Hi @weihuan1111, when I was looking at the capabilities for the blind on your account I didn't see a battery reading so I assumed it was a wired model. If it is a battery model then that would be the correct profile it should map to, you're right.

**Comment by weihuan1111** [comment]
@Brianj94 Yes, it is a battery model.
image

**Comment by Brianj94** [comment]
Hi @weihuan1111, I hope you are doing well. I sent an email last week outlining an issue that was found during UL testing. adding those details below:

There has been an issue identified in the testing with the FirmwareUpdate capability. 

In both the Android and iOS SmartThings app we are not seeing the firmware version display on the Information page for the device. The firmware version # should display where the red outlined boxes are on the screenshot below.

image

At this time we have exempted this failed test to proceed with closing the UL testing process. However, we will require this issue be resolved before we are able to publish the device officially as Works with SmartThings certified, and added into the SmartThings app catalog. 

Please let me know what questions you have regarding resolving this issue. Thank you!

**Comment by weihuan1111** [comment]
@Brianj94 How to display the version of device?

**Comment by Brianj94** [comment]
Hi @weihuan1111 , I am working on getting steps for how to display the version number. In the meantime the team is asking what the current firmware version is for this device. Could you provide that version number for us?

**Comment by Brianj94** [comment]
Spoke with the engineering team and we gather the firmware version from the OTA cluster, so if you implement that we should automatically display the version number. Can you confirm if you implement the OTA cluster? Thanks!

**Comment by weihuan1111** [comment]
@Brianj94  Yes， we implement the OTA cluster, you  can see the picture below
image

**Comment by Brianj94** [comment]
Hi @weihuan1111 , thank you for this screenshot. Engineering team would like to do some investigation from our side on this issue. 

Could you provide us with an email address to a SmartThings test account where this device has been added? Then please enable support access on that account so that we can look into that device (steps below):

* Go to SmartThings Web (my.smartthings.com)
* Log in to your Samsung Account
* Select Menu (⋮) and choose Settings
* Toggle on Account Data Access
* Select the time period and confirm

Let me know if you have any questions. 
Thank you!

**Comment by weihuan1111** [comment]
@Brianj94 Thank you. And i have allowed SmartThings Support permission to access to my data for a week with my another account: [huan.wei@thirdreality.ai](mailto:huan.wei@thirdreality.ai)

**Comment by Brianj94** [comment]
@weihuan1111 , we reviewed the device / hub logs on this account. The device should be checking in with the hub (OTA server) once per day to look for firmware updates, however we do not see the plug device check-in going back for multiple days. 

We suggest joining a new device (or remove and rejoin this one), and let us know what time it was re-joined. We will pull a new set of hub logs to see if there are any errors or insights into what is causing this behavior.

**Comment by weihuan1111** [comment]
@Brianj94 I have rejoin the smartthing hub, and connect the plug to the hub. The time i rejoin the smartthing hub is GMT+8 2023/05/12/11:09am 
I use Ubiqua to see the package infomation, the plug has already response to the hub about the version
f15c0257825f90007a26df833915ba0

**Comment by Brianj94** [comment]
Hi @weihuan1111 , Thanks for this info. It looks like the hub was rebooted after the device was added and we are missing the device join events. Could you please remove and re-add the plug one more time without rebooting the hub, and send me a timestamp for when the device was re-added?

Also can you confirm if the plug device is periodically sending the QueryNextImageRequest command in the OTA Cluster? 

Thank you.

**Comment by weihuan1111** [comment]
@Brianj94 I have re-add the plug, the time i re-add the plug  is GMT+8 2023/05/15/13:49

**Comment by Brianj94** [comment]
Thank you @weihuan1111, I worked with the Engineering team today to look into these logs. After the plug onboards we are not seeing any OTA cluster communication going on. 

The device should be identifying the hub as the OTA Server cluster and then sending a QueryNextImageRequest command to check for a FW update. This should take place within 5 minutes of the initial join/onboard and then at least once ever 24 hours. In the logs we are not seeing this check in happen. 

Please let us know if this is expected behavior with how the device is written, if you have any questions with what our team has found let me know. 

Thank you!

**Comment by weihuan1111** [comment]
@Brianj94  We have update our plug firmware, now, it will send a QueryNextImageRequest command after join the smartthing hub, but in app, still can not see the version. Can you help to check the log. 
And i have allowed SmartThings Support permission to access to my data for a week with my account: huan.wei@thirdreality.ai
The time i add the plug is GMT+8 2023/06/1/ 12:21
image

image

**Comment by weihuan1111** [comment]
@Brianj94 Hi, now, we have update our firmware version, and our plug will send QueryNextImageRequest command within 5 minutes of the initial join/onboard, after re-power and every 20 hours. You can see the screenshot below.
1f4c9151cce71d8b9d887f2541faf57

**Comment by Brianj94** [comment]
Hi @weihuan1111 , this looks great. I will let the team know and make sure this device officially finishes the certification process. I will let you know if any questions come up. Appreciate your efforts here!

**Comment by weihuan1111** [comment]
> Hi @weihuan1111, I have been looking through the edge drivers and doing a comparison for the devices that are listed on your account. This is my expectation for profile mapping once these devices are migrated to edge drivers. I also recommend certifying these ThirdReality devices so that your team has more control over the profiles and capabilities.
> 
> * ThirdReality Smart Button -> Zigbee-button one-button-battery.yml: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/blob/main/drivers/SmartThings/zigbee-button/profiles/one-button-battery.yml
> * ThirdReality Thermal & Humidity Sensor -> Zigbee-humidity-sensor humidity-temp-battery.yml: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/blob/main/drivers/SmartThings/zigbee-humidity-sensor/profiles/humidity-temp-battery.yml
> * ThirdReality smart Blind -> zigbee-window-treatment window-treatment-profile.yml: https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/blob/main/drivers/SmartThings/zigbee-window-treatment/profiles/window-treatment-profile.yml
> 
> We have upcoming driver migrations scheduled for mid April. I can not determine the exact date for your devices being migrated as there are fluid dates for when each specific driver may be migrated.
> 
> I hope this information is helpful. Thanks!

@Brianj94 Hi，have you start to migrate these three devices to the edge drivers?

**Comment by weihuan1111** [comment]
@Brianj94  Yes, our smart button has issue.  Previously, our button was recognized as a Third Reality Smart Button in smartthing and can also be used normally. However, recently, our button has been recognized as Thing on smartthing and cannot be used properly.  Our button's model is 3RSB22BZ, i search for it in edge drivers, i can not find it. It seems like it hasn't been migrated to edge drivers from DTHs. Do you have plan to migrate it ?

https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/78730

**Comment by Brianj94** [comment]
Hi @weihuan1111 , could I have you re-enable support access on this account? I would like to take a look at this device and see if I can find a proper Edge Driver that it should be migrated to. Steps below for convenience: 

Go to SmartThings Web (my.smartthings.com)
Log in to your Samsung Account
Select Menu (⋮) and choose Settings
Toggle on Account Data Access
Select the time period and confirm

Thank you,
Brian J

**Comment by weihuan1111** [comment]
@Brianj94 You've seen them before, see the screenshot below.  By the way, i have migrate the button from the DTHs to edge drivers,  https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/772   , can this be merged?

image

**Comment by Brianj94** [comment]
Hi @weihuan1111 , that DTH was migrated already to edge drivers. Since there was no manufacturer specific fingerprint for this device from Third Reality in the DTH, there was no fingerprint for Third Reality migrated to this edge driver. The device most likely had enough similar attributes to map to an existing fingerprint on that DTH.

In regards to a generic fingerprint, there was no generic fingerprint in the DTH either, so when the migration happened there was no generic fingerprint moved to this edge driver. Talking with our Edge team they confirmed there is also no button cluster for us to refer to for a generic fingerprint.

**Comment by weihuan1111** [comment]
you say the device most likely had enough similar attributes to map to an existing fingerprint on that DTH. But you can see this link https://github.com/SmartThingsCommunity/SmartThingsPublic/pull/78743

**Pull request merged**
