### PR TITLE
Fix abnormal rounding issue

### PR DESCRIPTION
**Pull request by HunsupJung**
Check all that apply

# Type of Change

- [ ] WWST Certification Request
     - If this is your first time contributing code:
          - [ ] I have reviewed the README.md file
          - [ ] I have reviewed the CODE_OF_CONDUCT.md file
          - [ ] I have signed the CLA
     - [ ] I plan on entering a WWST Certification Request or have entered a request through the WWST Certification console at developer.smartthings.com
- [x] Bug fix
- [ ] New feature
- [ ] Refactor

# Checklist

- [x] I have performed a self-review of my code
- [ ] I have commented my code in hard-to-understand areas
- [x] I have verified my changes by testing with a device or have communicated a plan for testing
- [ ] I am adding new behavior, such as adding a sub-driver, and have added and run new unit tests to cover the new behavior

# Description of Change
When Cooling or Heating Setpoint is Fahrenheit, there is a problem that the value below the decimal point is not properly set.
You can refer to link below for more information.
https://smartthings.atlassian.net/browse/IOTE-4627

# Summary of Completed Tests

### CODE REVIEW

**Comment by nickolas-deboom** [comment]
I think similar changes will be needed in matter-appliance for temperatureSetpointRange

**Review by nickolas-deboom — APPROVED** [review]

**Comment by HunsupJung** [comment]
@nickolas-deboom Thank you for your review. I will check that too

**Comment by HunsupJung** [comment]
@nickolas-deboom 
I was able to check same issue on matter-appliance driver and I updated a commit to fix it.

**Comment by nickolas-deboom** [comment]
Thank you @HunsupJung! I tested this change out and it solves the issue seen in the ticket. With the step set to 0.1 (default is 1 degree in the plugin), the capability no longer rounds to the nearest integer, which was causing setTemperatureSetpoint to be sent back to the driver with a rounded value.

**Pull request merged**
