### PR TITLE
Align mediaGroup capabilites & CmdHandlers

### PR DESCRIPTION
**Pull request by TheMegamind**
mediaGroup capabilities & CmdHandlers are misaligned

### CODE REVIEW

**Comment by TheMegamind** [comment]
Is anybody available to review this PR?  While this is one of at least three significant issues with the Edge integration, this one is the most obvious and should be the easiest to fix.  Perhaps @dljsjr ?

**Comment by dljsjr** [comment]
@TheMegamind Thanks for the PR, I'll take a look tomorrow. I was out of the office last week and still getting spun back up. I think we identified this bug internally already as well so should be easy enough to verify the fix.

**Comment by TheMegamind** [comment]
Thanks, I've got a related project I'm working on, and this issue has essentially brought things to a halt. :)

There's also a [PR to include the `replace` action with](https://github.com/SmartThingsCommunity/SmartThingsEdgeDrivers/pull/577) the playPreset command if you wouldn't mind looking at that as well.

**Comment by dljsjr** [comment]
@TheMegamind Sorry for the delay, I needed to investigate the `replace` action change from your other PR as it is present here as well. I provided feedback there on that change.

That said, if you were to remove that change from this PR and squash your commits down, the actual bugfix itself looks good to me.

**Review by dljsjr — CHANGES_REQUESTED** [review]
@TheMegamind Sorry for the delay, I needed to investigate the `replace` action change from your other PR as it is present here as well. I provided feedback there on that change.

That said, if you were to remove that change from this PR and squash your commits down, the actual bugfix itself looks good to me.

**Comment by TheMegamind** [comment]
@dljsjr Ok, I knew I made a new kind of mess when I added the "replace" PR, but was traveling and couldn't remember how to undo the damage. I haven't done that in a while, but will figure it out.

**Comment by TheMegamind** [comment]
@dljsjr Lol, called in the local cavalry to help me fix my mess and left two guys who could build rocket ships scratching their heads. Maybe we should just close 575 and let you do it the right way.

**Pull request closed without merging**
