### PR TITLE
add heiman motion sensor  for WWST

### PR DESCRIPTION
**Pull request by Leo2442926161**
Add heiman motion sensor for WWST.

Hi @lelandblue ,
Could you help to close the other PRs because I can't modify those PRs, I will resubmit motion sensor and door sensor separately. Thanks.

### CODE REVIEW

**Review by greens — APPROVED** [review]

**Review by lelandblue — APPROVED** [review]
Approved, thank you.

**Comment by Leo2442926161** [comment]
Hi @lelandblue ,
Thank you all for your help, when will the PR be merged to SmartThingEdgeDriver repository?

**Comment by Leo2442926161** [comment]
@lelandblue  I would like to ask another question here, not sure if it appropriate.

We've got matter 1.2 certication for smoke and CO sensors, I'd like to ask when will SmartThing will support Matter Smoke & CO sensor? is there anything that we can do for make this in progress? Thanks.

**Comment by lelandblue** [comment]
Hey @Leo2442926161 We will be reaching out shortly with an update to both of your questions via email. Please look for that communication. Thank you for your time.

**Comment by Leo2442926161** [comment]
Thank you @lelandblue

**Pull request merged**
