### PR TITLE
Add firmwareUpdate capability to matter and zb profiles

### PR DESCRIPTION
**Pull request by samadDotDev**

### CODE REVIEW

**Comment by ctowns** [comment]
Please ignore the failure in the "Check for duplicate profiles" step below. This is due to an issue with the duplicate profile script not handling profiles without categories and not properly handling preferences. It is an issue with the script and not with this PR.

@greens do you know if there was a specific reason why `firmwareUpdate` was excluded from all matter drivers?

**Comment by greens** [comment]
@ctowns I think we just didn't know it should have been included. As far as I knew, `firmwareUpdate` was just for Zigbee and no one told us otherwise.

**Review by greens — APPROVED** [review]

**Review by ctowns — APPROVED** [review]

**Review by hubTab — APPROVED** [review]

**Review by Con-Tejus — APPROVED** [review]

**Review by cjswedes — APPROVED** [review]
Is it true that going forward this capability should be included in every matter profile without exceptions?

**Comment by samadDotDev** [comment]
> Is it true that going forward this capability should be included in every matter profile without exceptions?

I believe so. The hubs running 0.47.x will emit `firmwareUpdate` capability with the current software version post device-onboarding for all matter devices. Additionally, if they undergo an update whether through our hub or any other fabric, the `availableVersion` attribute and update statuses will be reflected in the capability throughout the process.

**Comment by greens** [comment]
feel free to merge @samadDotDev

**Pull request merged**
