### PR TITLE
[SONOFF] add multipurpose sensor

### PR DESCRIPTION
**Pull request by mingwei0827**

### CODE REVIEW

**Comment by lelandblue** [comment]
Closing PR. If there are questions please reach out to partners@smartthings.com

**Review by greens — APPROVED** [review]

**Review by dljsjr — APPROVED** [review]

**Comment by greens** [comment]
because this PR was closed it will need a new commit in order to trigger channel recreation

**Comment by liangjia2019** [comment]
> because this PR was closed it will need a new commit in order to trigger channel recreation

I just saw the situation with this close and I have sent an email（partners@smartthings.com） asking the relevant team how to handle it

**Comment by mingwei0827** [comment]
> because this PR was closed it will need a new commit in order to trigger channel recreation

Hi Green:
    i submit new commit, please help us proceed to the next step.thanks

**Comment by greens** [comment]
all good, invitation link up now

**Comment by lelandblue** [comment]
Hello @mingwei0827 - Please sign the CLA when you get the chance. Thank you.

**Comment by lelandblue** [comment]
Closed PR. Please reach out to partners@smartthings.com if there are questions.

**Pull request closed without merging**
