### PR TITLE
Added unit tests to cover `create_device` calls for mcd devices

### PR DESCRIPTION
**Pull request by dsobierajsk**
@SmartThingsCommunity/srpol-pe-team

### CODE REVIEW

**Review by KKlimczukS — APPROVED** [review]

**Comment by KKlimczukS** [comment]
@dsobierajsk let's wait for changes in the scripting-engine before merging this one

**Comment by dsobierajsk** [comment]
It is failing because it probably does not see the latest version of lua libs (the changes were released about 19 hours ago). But locally all tests passes.

**Review by greens — APPROVED** [review]
Looks good, but like Konrad said, wait until 46.

**Comment by dsobierajsk** [comment]
> Looks good, but like Konrad said, wait until 46.

Then I will add also tests for other mcd devices.

**Review by Mztea928 — APPROVED** [review]

**Pull request merged**
