### PR TITLE
[CHAD-8941] Changed the range of Z-Wave dimmers to [1,100]

### PR DESCRIPTION
**Pull request by Bhavik-T**

### CODE REVIEW

**Comment by greens** [comment]
@bflorian does this look kosher to you?

@Bhavik-T I think you're on the right track. This particular profile is for a zigbee dimming remote, but I do think we'll want to apply the [1,100] range to *all* profiles which include the Switch Level preference.

**Review by greens — APPROVED** [review]
Looks good but we're waiting on upstream changes.

**Comment by lelandblue** [comment]
Hey @bflorian Can you please check this?

**Comment by iplantemn** [comment]
@greens @bflorian updated for the model changes. Not sure why the unit tests are failing, I just changed the profile YMLs

**Comment by greens** [comment]
@ctowns when you get time could you update this PR to align to the new format

**Review by greens — APPROVED** [review]
Looks good but we'll probably have to do this again with the profiles that have been added since this was created.

**Comment by greens** [comment]
@ctowns could you resolve the conflict with the `inovelli-dimmer` profile?

**Pull request merged**
