### PR TITLE
[CHAD-8804] zigbee-thermostat/zigbee-valve/zwave-sensor: Set correct possible options for power source

### PR DESCRIPTION
**Pull request by Bhavik-T**
Updated all zigbee-valve profiles. All powerSources now only consist of battery and mains.

### CODE REVIEW

**Review by greens — COMMENTED** [review]
we probably want to do this anywhere we have the `powerSource` capability

**Review by greens — APPROVED** [review]

**Comment by lelandblue** [comment]
@greens Do we want Bob to also review this one? Even though your review is complete?

**Comment by greens** [comment]
@lelandblue this is more just waiting on the feature being released. I tagged Bob in some of the other ones to make sure he thought the formatting looked good to him.

**Comment by iplantemn** [comment]
@greens @bflorian updated capability configuration

**Comment by lelandblue** [comment]
@ctowns Can you change "configuration:" to " config:" please on this PR?

**Pull request merged**
